name: Prebuild

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
    - run: yarn apply-libuiohook-patch
    - run: yarn --frozen-lockfile
    - run: yarn prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: prebuilds

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
    - run: |
        sudo apt-get update
        sudo apt-get install -y libxrandr-dev libxtst-dev
    - run: yarn apply-libuiohook-patch
    - run: yarn --frozen-lockfile
    - run: yarn prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: prebuilds

  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
    - run: yarn apply-libuiohook-patch
    - run: yarn --frozen-lockfile
    - run: yarn prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: darwin
        path: prebuilds
